account/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'account'
urlpatterns = [
    path('sign-up/id', views.signup, name='signup'),     # register
    path('sign-up/key', views.signup_password, name='signup-pwd'),
    path('sign-in', views.signin, name='signin'),
    # path('sign-in', views.signin, name='signin'),
    # path('logon', auth_views.LoginView.as_view()),
    path('<int:user_id>', views.profile, name='profile'),
    path('', views.profile, name='profile'),
    path('sign-out/request', views.signout_request, name='signout_request'),
    path('sign-out', views.signout, name='signout'),
    # re_path(r'^connection$', views.connect, name='connection'),
]

# re_path(r'^articles/(?P<tag>.+)', views.list_articles_by_tag), 
# re_path(r'^articles/(?P<year>\d{4})/(?P<month>\d{2})', views.list_articles),  

product/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views


app_name = 'product'
urlpatterns = [
    # url(r'^index/$', views.index), 
    # url(r'^home/$', views.index), 
    path('', views.index, name='home'),
    # re_path(r'^result/$', views.result, name='result'),
    path('result/<str:user_query>', views.result, name='result'),
    path('favorite', views.favorite, name='favorite'),
    path('parse/favorite', views.parse_favorite, name='parse_favorite'),
    # url(r'^(?P<_product_id>[0-9]+)/$', views.product, name='info'),
    path('product/<int:product_id>/from/<str:page_origin>', views.product, name='product'),
    path('product/<int:product_id>/from/<str:page_origin>/<str:product_id_origin>/<str:user_query>', views.product, name='product'),
    # url(r'^notices/$', views.notice, name='notice'),
    path('notices', views.notice, name='notice'),
    ]

product/models.py
from django.db import models
from django.contrib.auth import get_user_model


class ZProduct(models.Model):
    code = models.BigIntegerField('Code', primary_key=True, default=0, null=False, unique=True)
    brands = models.CharField('Marque', max_length=256, null=True)
    name = models.CharField('Nom', max_length=256)
    url = models.URLField('URL', null=True)
    stores = models.CharField('Stores', max_length=256, null=True)
    # category_hierarchy = models.IntegerField(null=True)
    nutrition_grades = models.CharField('Nutri-Score', max_length=1, null=True)
    nova_group = models.SmallIntegerField('Nova', null=True)
    nutrition_score_fr = models.SmallIntegerField('Nutrition score', null=True)
    nutrition_score_uk = models.SmallIntegerField('Nutrition score', null=True)
    nutrition_score_beverage = models.SmallIntegerField('Nutrition score beverage', null=True)
    fat_100g = models.FloatField('Matières grasses / Lipides', null=True)
    saturated_fat_100g = models.FloatField('Acides gras saturés', null=True)
    sugars_100g = models.FloatField('Sucres', null=True)
    salt_100g = models.FloatField('Sel', null=True)
    unique_scans_n = models.SmallIntegerField('Popularité', null=True)
    created_t = models.BigIntegerField('Date de création', null=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    last_modified_t = models.BigIntegerField('Date de mise à jour', null=False, default=0)
    # last_modified = models.DateTimeField(auto_now_add=True)
    update_t = models.DateTimeField("Date d'enregistrement", auto_now_add=True, null=True)
    image_url = models.URLField('Image URL', null=True)
    
    categories = models.ManyToManyField('ZCategory', through='ZCategory_Product', related_name='products', blank=True)
    searchers = models.ManyToManyField(get_user_model(), through='ZSearch', related_name='searches', blank=True)
    users = models.ManyToManyField(get_user_model(), through='ZFavorite', related_name='favorites', blank=True)
    alternatives = models.ManyToManyField('self', related_name='substituted', symmetrical=False, blank=True)

    class Meta:
        verbose_name = "Produit"
        verbose_name_plural = "Produits"
        # constraints = [
        #     models.UniqueConstraint(fields=['brands', 'name'], name='product_identifier_unique'),
        # ]

    def __str__(self):
        return "{} - {} - {}".format(self.code, self.brands, self.name)


class ZCategory(models.Model):
    identifier = models.CharField(max_length=256, primary_key=True, unique=True)
    label = models.CharField(max_length=256, null=True)

    def __str__(self):
        return "{} - {}".format(self.identifier, self.label)

class ZCategory_Product(models.Model):
    product = models.ForeignKey('ZProduct', on_delete=models.CASCADE)
    category = models.ForeignKey('ZCategory', on_delete=models.CASCADE)

    hierarchy_index = models.PositiveSmallIntegerField(default=0, null=False)
    date = models.DateTimeField(auto_now=True)

    # alternatives = models.ManyToManyField(ZFavorite, related_name='zsearches', blank=True)

class ZFavorite(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    favorite = models.ForeignKey('ZProduct', on_delete=models.CASCADE)
    # alternatives = models.ManyToManyField(ZFavorite, related_name='zsearches', blank=True)

    date = models.DateTimeField(auto_now=True)

class ZSearch(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    target = models.ForeignKey('ZProduct', on_delete=models.CASCADE)
    favorite_alternatives = models.ManyToManyField(ZFavorite, related_name='zsearches', blank=True)

    date = models.DateTimeField(auto_now=True)


# class Booking(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True)
#     contacted = models.BooleanField(default=False)
#     album = models.OneToOneField(Album)
#     contact = models.ForeignKey(Contact, on_delete=models.CASCADE)


# class ZContact(models.Model):
#     name = models.CharField(max_length=200)
#     email = models.EmailField(max_length=100)

#     def __str__(self):
#         return self.name

#     class Meta:
#         verbose_name = "Utilisateur"
#         verbose_name_plural = "Utilisateurs"

product/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(
        label='Nom',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=True)


class QueryForm(forms.Form):
    query = forms.CharField(
        label='Query',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=True
        )

class FavoriteForm(forms.Form):
    code = forms.IntegerField(
        label='Code',
        min_value=0,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        # widget=forms.NumberInput(attrs={'class': 'form-control'}),
        required=True
        )
    is_favorite = forms.BooleanField(
        label='Favorite state',
        widget=forms.CheckboxInput(attrs={'class': 'form-control'}),
        required=False)

product/views.py
import os, sys
import json

import logging


from django.http import HttpResponse, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .models import ZProduct, ZCategory, ZSearch, ZCategory_Product
from .forms import QueryForm, FavoriteForm


DIR_BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
print(DIR_BASE)
sys.path.append(DIR_BASE)
from zopynfacts import products

# sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))


# Get an instance of a logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def index(request):
    # print(ZContact.objects.all())
    # ZContact.objects.filter(name="Mike")[-1])
    # message = "This is the home page, the user is {}".format(ZContact.objects.filter(name="mike")[0])

    # album = get_object_or_404(Album, pk=album_id)
    # artists = [artist.name for artist in album.artists.all()]
    # artists_name = " ".join(artists)
    
    # context = {
    #     'album_title': album.title,
    #     'artists_name': artists_name,
    #     'album_id': album.id,
    #     'thumbnail': album.picture
    # }
    
    context = {'page': 'home'}
    user_query = ""
    response = None

    if request.method == 'POST':
        # POST method
        
        form = QueryForm(request.POST)
        context['page'] = 'result'
        context['query'] = user_query
        if form.is_valid():
            # Form is correct.
            # We can proceed to booking.
            user_query = request.POST.get('query')

            # return HttpResponseRedirect(reverse('product:result', args=[user_query]))
            response = redirect('product:result', user_query=user_query)

        else:   # [TODO]: is not necessary
            # Form data doesn't match the expected format.
            # Add errors to the template.
            context['errors'] = form.errors.items()
            print('Form error')
            response = render(request, 'product/list.html', context)
    else:
        # GET method.
        
        response = render(request, 'product/index.html', context)
    
    return response


def result(request, user_query):

    context = {'page':'result', 'product_lst':[]}

    # Get most popular product according to query

    ## Get from local db
    product_targeted_mdl = search_product(user_query)

    ## Get from remote source db
    if not product_targeted_mdl:

        logger.info('User query: {} not in local db'.format(user_query), exc_info=True, extra={
            # Optionally pass a request and we'll grab any information we can
            'request': request,
            })

        r_json = products.search(user_query, locale='fr')
        if r_json['products']:
            product_dct = r_json['products'][0]

            # Get product data
            product_data_dct = products.extract_data(product_dct)

            # Update or insert product into db
            product_targeted_mdl = set_product_model(product_data_dct)

    if product_targeted_mdl:

        if request.user.is_authenticated:
            # Save searched product according to authenticated user
            request.user.searches.add(product_targeted_mdl)

            # Get user's favorite product
            favorite_product_mdl_lst = request.user.favorites.all()
            context['favorite_lst'] = favorite_product_mdl_lst

        # alternative_product_lst = products.nutrition(product_data_dct, 7)
        # for alternative_data_dct in alternative_product_lst:
        #     product_targeted_mdl.alternatives.add( set_product_model(alternative_data_dct) )
        alternative_product_lst = get_alternative_product(product_targeted_mdl.code, 12, 3)
        for alternative_mdl in alternative_product_lst:
            product_targeted_mdl.alternatives.add(alternative_mdl)

        context['product_lst'] = product_targeted_mdl.alternatives.all().order_by('nutrition_grades', 'nova_group', '-unique_scans_n')

    else:
        logger.info('User query: {} not found'.format(user_query), exc_info=True, extra={
            # Optionally pass a request and we'll grab any information we can
            'request': request,
            })

    #     product_data_dct = {}
    #     alternative_product_lst = []

    context['query'] = user_query
    context['product_target'] = product_targeted_mdl
    return render(request, 'product/list.html', context)


@login_required()      # By default, use LOGIN_URL in settings
def favorite(request):

    product_lst = request.user.favorites.order_by('name')[:]

    context = {'page':'favorite'}
    context['product_lst'] = product_lst
    context['favorite_lst'] = product_lst

    return render(request, 'product/list.html', context)


def product(request, product_id, page_origin=None, product_id_origin=None, user_query=None):

    if request.user.is_authenticated:
        # Get user's favorite product
        favorite_lst = request.user.favorites.all()

    try:
        product = ZProduct.objects.get(code=int(product_id))
    except ZProduct.DoesNotExist:
        message = "Unkown product id"
    else:
        message = "This is the product #{}-{} description page".format(product_id, product.name)

    return render(request, 'product/product.html', locals())


def parse_favorite(request):
    
    context = {}

    if request.method == 'POST':

        code = int(request.POST.get('code'))
        favorite = request.POST.get('favorite')
        print(type(code), code)
        print(type(favorite), favorite)

        if favorite == 'true':
            favorite = True
        else:
            favorite = False

        print(code)
        print(favorite)

        # Update or create favorite product into db
        user_mdl = get_user_model().objects.get(username=request.user.username)
        print(request.user)
        print(user_mdl)
        try:
            favorite_mdl = ZProduct.objects.get(code=int(code))
        except ZProduct.DoesNotExist:
            print("CRITICAL ERROR GETINNG FAVORITE PRODUCT")
        else:
            if favorite:
                user_mdl.favorites.add(favorite_mdl)
            else:
                user_mdl.favorites.remove(favorite_mdl)
            favorite = not favorite
            print(favorite)

        print(user_mdl.favorites.all())
        context = {'code' : code, 'favorite' : favorite}

    return HttpResponse( json.dumps( context ) )


def notice(request):

    return render(request, 'product/notice.html', locals())


def set_product_model(product_data_dct):
    """
    Update or insert product into database
    """

    product_targeted, created = ZProduct.objects.get_or_create(code=product_data_dct['code'])
    print("Product created:", created, "; ", product_targeted)

    if created or product_targeted.last_modified_t < product_data_dct['last_modified_t']:

        product_targeted.categories.clear()

        code = product_data_dct['code']
        categories_hierarchy_lst = product_data_dct['categories_hierarchy']
        nutrient_levels = product_data_dct['nutrient_levels']
        image = product_data_dct['image']
        del product_data_dct['code']
        del product_data_dct['categories_hierarchy']
        del product_data_dct['nutrient_levels']
        del product_data_dct['image']

        product_targeted, created = ZProduct.objects.update_or_create(defaults=product_data_dct, code=code)
        if created:
            # TODO: critical error
            print("/!\\ CRITICAL ERROR: PRODUCT TARGETED CREATED AGAIN /!\\")

        for idx, category_id in enumerate(categories_hierarchy_lst):

            category_mdl, created = ZCategory.objects.get_or_create(identifier=category_id)
            print(category_mdl, created)
            product_targeted.categories.add(category_mdl, through_defaults={'hierarchy_index': idx} )
            # category_mdl.products.add(product_targeted, through_defaults={'hierarchy_index': idx} )
            # relation = ZCategory_Product.objects.create(product=product_targeted, category=category_mdl, hierarchy_index=idx)
            # relation.save()

        product_data_dct['code'] = code
        product_data_dct['categories_hierarchy'] = categories_hierarchy_lst
        product_data_dct['nutrient_levels'] = nutrient_levels
        product_data_dct['image'] = image

        # brands = product_data_dct['brands']
        # product_targeted.name = product_data_dct['name']
        # product_targeted.save()

    # categories_hierarchy
    # nutrient_levels
    # created_t
    # last_modified_t

    return product_targeted


def search_product(query):

        # Parse user query

        ## delete stop word
        print('> User Query:', query)

        word_lst = query.split()
        # print(word_lst)


        # Search targeted product

        ## Get all products
        product_lst_db = ZProduct.objects.all()
        # print_product_list(product_lst_db)

        targeted_product_lst_db = ZProduct.objects.none()

        for idx, word in enumerate(word_lst):
            print(idx, '-', word)
    
            ## Filter product by brand and name
            filtered_product_lst_db = ZProduct.objects.none()
            
            filtered_product_lst_db = filtered_product_lst_db.union(product_lst_db.filter(brands__icontains=word))
            # print_product_list(filtered_product_lst_db)

            filtered_product_lst_db = filtered_product_lst_db.union(product_lst_db.filter(name__icontains=word))
            # print_product_list(filtered_product_lst_db)
            
            ## Get targeted product
            if not targeted_product_lst_db:
                targeted_product_lst_db = (filtered_product_lst_db)
            else:

product/templates/product/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pur Beurre</title>

    {% load static %}

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'product/vendor/fontawesome-free/css/all.min.css' %}">

    <!-- Font Awesome Icons -->
    <link rel="shortcut icon" href="{% static 'product/img/logo_pur_beurre-favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'product/img/logo_pur_beurre-favicon.png' %}" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="{% static 'product/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS - Includes Bootstrap -->
    <link rel="stylesheet" href="{% static 'product/css/creative.min.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/zstyle.css' %}">
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'product/css/icons.css' %}" /> {% endcomment %}

</head>

<body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">
            {% if page == 'home' %}
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
            {% else %}
            <a class="navbar-brand js-scroll-trigger" href="{% url 'product:home' %}">
            {% endif %}
                <img id="zlogo" src="{% static 'product/img/logo_pur_beurre.png' %}" alt="Home Top"> Pur Beurre
                <!-- <img class="img-fluid" src="{% static 'product/img/logo_pur_beurre.svg' %}" alt=""> Pur Beurre -->
            </a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">

                  <li class="nav-item">{% include "product/query.html" %}</li>
                  <li class="nav-item">
                    {% if user.is_authenticated %}
                    {% comment %} <a id=profile_a class="nav-link js-scroll-trigger" href="{% url 'account:profile' user.id %}">Mon Compte {{ user.username }}</a> {% endcomment %}
                    <a id=profile_a class="nav-link js-scroll-trigger" href="{% url 'account:profile'%}" title="Compte">
                      <i class="fas fa-2x fa-user-circle mb-4"></i> {{ user.username }}</a>
                    {% else %}
                    <a id=signin_a class="nav-link js-scroll-trigger" href="{% url 'account:signin' %}" title="Connexion"><i class="fas fa-2x fa-sign-in-alt mb-4"></i></a>
                    {% endif %}
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a id=favorite_a class="nav-link js-scroll-trigger" href="{% url 'product:favorite' %}" title="Mes aliments">
                      <i class="fas fa-2x fa-carrot mb-4"></i></a></li>
                      {% comment %} <img id="zcarrot" src="{% static 'product/img/noun_Carrot_29691.png' %}" alt="Mes aliments"></a></li> {% endcomment %}
                  <li class="nav-item">
                    <a id=signout_a class="nav-link js-scroll-trigger" href="{% url 'account:signout_request' %}" title="Déconnexion">
                      <i class="fas fa-2x fa-sign-out-alt mb-4"></i></a></li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block mastead %}
    <!-- Masthead -->
    <header class="masthead masthead_product">
      <div class="container h-50">
        <div class="row h-50 align-items-center justify-content-center text-center">
          {% block masthead_title %}{% endblock %}
        </div>
      </div>
    </header> 
    {% endblock %}     
    
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="bg-light py-5">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
              <div><a id=notice_a class="d-block" href="{% url 'product:notice' %}">Mentions légales</a></div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
              <a id=contact_lnk class="d-block" href="{% url 'product:home' %}#contact">Contact</a>
            </div>
          </div>

          {% comment %} <div class="small text-center text-muted">Copyright &copy; 2019 - Start Bootstrap</div> {% endcomment %}
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'product/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'product/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'product/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'product/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'product/js/creative.min.js' %}"></script>

</body>

</html>

product/templates/product/favorite.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>

product/templates/product/product.html
{% extends 'product/base.html' %}

{% load static %}

{% block mastead %}
<!-- Masthead -->
<header class="masthead masthead_list">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h2 class="text-uppercase text-white font-weight-bold">
          {% if user.is_authenticated %}
          <a id={{ product.code }} href="javascript:;" data-state="{% if product in favorite_lst %}false{% else %}true{% endif %}" onclick="set_favorite(this.id, this.getAttribute('data-state'))">
              {% if product in favorite_lst %}
              <i class="fas fa-1x fa-heart mb-4"></i>    {% comment %} fa-star {% endcomment %}
              {% else %}
              <i class="far fa-1x fa-heart mb-4"></i>
              {% endif %}
          </a>
          - 
          {% endif %}

          {{ product.brands }}<br>{{ product.name }}
          </h2>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 col-md-6 align-self-baseline text-center">
        <div class="mt-5">
            {% comment %} <!-- <p class="text-white-75 font-weight-light mb-5">Start Bootstrap can help you build better websites using the Bootstrap framework! Just download a theme and start customizing, no strings attached!</p> --> {% endcomment %}
            {% comment %} <!-- <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a> --> {% endcomment %}
          {% if product.image_url %}
          <p><img class="img-fluid" src={{ product.image_url }} alt=""></p>
          {% else %}
          <i class="fas fa-4x fa-globe text-primary mb-4"></i>
          {% endif %}
          {% comment %} <h6 class="h6 mb-2">[ {{ product.zcategory_product_set.hierarchy_index.0 }} ]</h6> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</header> 
{% endblock %}     

{% block content %}

<section id="product_info" class="page-section">
  <div class="container">
    <div>
      <p class="text-muted mb-0">Retour à
        {% if page_origin == 'result' %}
        {% comment %} <p class="text-muted mb-0"><a id=notice_a class="d-block" href="{% url 'product:result' product_target.code %}"></a></p> {% endcomment %}
         Recherche > <a id='result_back_link' class="" href="{% url 'product:result' user_query %}">{{ user_query }}</a>
        {% elif page_origin == 'favorite'%}
         <a id='favorite_back_link' class="" href="{% url 'product:favorite' %}">Mes aliments</a>
        {% endif %}
      </p>
    </div>
    <hr class="divider my-4">
    <div class="row justify-content-center">
      {% comment %} <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0"> {% endcomment %}
      <div class="col-lg-6 col-md-6 align-self-center text-justify">
        <div class="mt-5">
          {% if product.nutrition_grades == 'a' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-a.svg' %}" alt="{{ product.nutrition_grades }}">
          {% elif product.nutrition_grades == 'b' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-b.svg' %}" alt="{{ product.nutrition_grades }}">
          {% elif product.nutrition_grades == 'c' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-c.svg' %}" alt="{{ product.nutrition_grades }}">
          {% elif product.nutrition_grades == 'd' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-d.svg' %}" alt="{{ product.nutrition_grades }}">
          {% elif product.nutrition_grades == 'e' %}<img class="img-fluid" src="{% static 'product/img/nutriscore-e.svg' %}" alt="{{ product.nutrition_grades }}">
          {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>
          {% endif %}

          {% if product.nova_group == 1 %}<img class="img-fluid" src="{% static 'product/img/nova-group-1.svg' %}" alt="{{ product.nova_group }}">
          {% elif product.nova_group == 2 %}<img class="img-fluid" src="{% static 'product/img/nova-group-2.svg' %}" alt="{{ product.nova_group }}">
          {% elif product.nova_group == 3 %}<img class="img-fluid" src="{% static 'product/img/nova-group-3.svg' %}" alt="{{ product.nova_group }}">
          {% elif product.nova_group == 4 %}<img class="img-fluid" src="{% static 'product/img/nova-group-4.svg' %}" alt="{{ product.nova_group }}">
          {% else %}<i class="fas fa-2x fa-globe text-primary mb-4"></i>
          {% endif %}
        </div>
      </div>
      <div class="col-lg-6 col-md-6 align-self-center text-justify">
        <div class="mt-5">
          <p>Repère nutritionnel pour 100 g : {{ product.nutrition_score_fr }}</p>
          <div>
            <p class="text-muted mb-0">{{ product.fat_100g }} g de <strong>Matières grasses / Lipides</strong></p>
            <p class="text-muted mb-0">{{ product.saturated_fat_100g }} g d'<strong>Acides gras saturés</strong></p>
            <p class="text-muted mb-0">{{ product.sugars_100g }} g de <strong>Sucres</strong></p>
            <p class="text-muted mb-0">{{ product.salt_100g }} g de <strong>Sel</strong></p>
          </div>
        </div>
      </div>
    </div>
    <hr class="divider my-4">
    <h2 class="text-center mt-0"><a class="d-block" href="https://fr.openfoodfacts.org/produit/{{ product.code }}">Voir la fiche d'OpenFoodFacts</a></h2>
  </div>
</section>

<script>
    var parse_favorite_url = "{% url 'product:parse_favorite' %}"
</script>
<script src="{% static 'product/js/zajax.js' %}"></script>
<script src="{% static 'product/js/zproduct.js' %}"></script>

{% endblock %}

product/templates/product/query.html
<form class="form-inline justify-content-center" action="{% url 'product:home' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" class='form-control' name="query" value="">
        <button type="submit" class="btn btn-success">Rechercher</button>
    </div>
</form>

product/templates/product/result.html
<div class="col-lg-12">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}
    </h2>
    <hr class="detail-separator">
</div>